### ISSUE TITLE
failwith crash

### ISSUE THREAD

**Issue by mro** [Gopiandcode/ocamlot#1]
https://github.com/Gopiandcode/ocamlot/blob/11dc838d784bd9ce1af8d1cfc8a87edb3850c300/lib/activitypub/decode.ml#L306

You probably mean `fail`.

**Comment by Gopiandcode** [comment]
Ah, yes, good catch! Thanks @mro ! (Thankfully, I think this was on a codepath that is only executed inside the worker which is already wrapped in a try-catch to prevent exceptions from terminating the entire server).

Anyway, by the way, thanks for taking a look at my code! I guess we've both been working on OCaml+Activitypub projects, so I'd be curious to hear what you think, or what problems you ran into in your work.
